# Generated by Django 4.0.5 on 2022-08-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_item_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eu', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='available',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='available',
            name='size',
        ),
        migrations.AddField(
            model_name='available',
            name='size',
            field=models.ManyToManyField(to='eshop.size'),
        ),
    ]
