# Generated by Django 4.0.5 on 2022-08-09 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_size_available_count_remove_available_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available',
            name='item',
        ),
        migrations.AddField(
            model_name='available',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='eshop.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='available',
            name='size',
            field=models.ManyToManyField(blank=True, to='eshop.size'),
        ),
    ]
