# Generated by Django 4.0.5 on 2022-08-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0006_rename_count_available_count_of_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='size',
            field=models.ManyToManyField(to='eshop.size'),
        ),
    ]
