# Generated by Django 4.0.5 on 2022-08-10 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_available_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available',
            name='size',
        ),
        migrations.AddField(
            model_name='available',
            name='size',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='eshop.size'),
            preserve_default=False,
        ),
    ]
