# Generated by Django 4.0.5 on 2022-08-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_remove_available_size_available_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Available',
            new_name='Availability',
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='item',
            new_name='product',
        ),
    ]
