# Generated by Django 4.0.5 on 2022-08-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0011_cart_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
    ]
