# Generated by Django 4.0.5 on 2022-08-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0012_remove_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(default=44, on_delete=django.db.models.deletion.CASCADE, to='eshop.size'),
            preserve_default=False,
        ),
    ]
